manoharan-lab/holopy

holopy/core/marray.py
Added spacing setter to ImageSchema to properly handle scalar spacing inputs for colour images
=> Fixed spacing for colour images

holopy/core/marray.py
=> Fixed Resampling to function with single input size

holopy/core/process/simulate_noise.py, holopy/fitting/mcmc.py, holopy/scattering/tests/test_lowlevel.py
Fixed a scattering test which was using deprecated Bessel functions. A chunk of changes to inference stuff to make results presentation better.
=> Test fix and inference results improvements

holopy/scattering/scatterer/__init__.py, holopy/scattering/scatterer/bisphere.py, holopy/scattering/scatterer/capsule.py, holopy/scattering/scatterer/cylinder.py, holopy/scattering/scatterer/ellipsoid.py, holopy/scattering/scatterer/sphere_builtin.py, holopy/scattering/theory/dda.py
=> make ellipsoid able to rotate.

holopy/scattering/theory/dda.py
move dda's calculation of scattering matricies into a seperate function to better mirror what happens in other theories and hopefully allow more sharing of code with the new tmatrix code when it lands
=> Seperate function for dda scattering matrix calculation 

holopy/scattering/tests/test_multisphere.py
to confirm multisphere works with new calculation interface
=> fix a multisphere test

.gitignore, setup.py
This is work I was doing while investigating how to distribute with conda-forge. I'm pushing for now since I'm working on other stuff currently.
=> Cleaned up setup.py a little bit and updated dependencies.

holopy/core/io/serialize.py, holopy/core/marray.py, holopy/core/tests/test_io.py, holopy/core/tests/test_marray.py, holopy/fitting/fit.py, holopy/fitting/model.py, holopy/fitting/tests/test_fit.py, holopy/fitting/tests/test_minimizer.py, holopy/fitting/tests/test_model.py, holopy/fitting/tests/test_nmpfit.py, holopy/fitting/tests/test_series.py, holopy/inference/noise_model.py, holopy/inference/tests/test_mcmc.py, holopy/inference/tests/test_pickle.py, holopy/inference/timeseries.py, holopy/propagation/tests/test_propagation.py, holopy/scattering/calculations.py, holopy/scattering/theory/scatteringtheory.py
Also deleted a couple of chunks of code that were duplicated or no longer needed.
We now want to use yaml's defualt function saving by import path, rather than the partial implementation of saving function bodies I had.
=> Convert rest of code to use new calculation interface

holopy/propagation/convolution_propagation.py
This adds back in the Cascaded-free-space propagation code and exposes it publicly in propagate. This partially addresses #101, though we will still want to either document it better and/or automatically apply it.
=> re-add cfsp (per issue #101)

holopy/core/metadata.py, holopy/core/tools/__init__.py, holopy/core/tools/math.py, holopy/core/tools/utilities.py, holopy/fitting/fit.py, holopy/fitting/minimizer.py, holopy/fitting/model.py, holopy/inference/noise_model.py, holopy/inference/tests/test_pickle.py, holopy/scattering/calculations.py, holopy/scattering/theory/mie.py, holopy/scattering/theory/scatteringtheory.py
Start unifying code of inference and fitting where it makes sense.
Get rid of unnecessary stacking/unstacking (helps performance).
=> Clean up and speed up fitting/inference

.travis.yml, holopy/fitting/model.py, holopy/fitting/tests/test_fit.py, run_nose.py
Tell travis to use xarray, and fix the run_nose script so that it will report errors correctly.
=> Fix travis and run_nose

holopy/core/metadata.py, holopy/scattering/tests/test_multisphere.py
makes coordinate calculations ~5x faster
=> add back in storing seperate x, y, and z coords when flattening

docs/source/pyplots/basic_ps_recon.py, docs/source/pyplots/basic_recon.py, docs/source/reference/holopy.propagation.rst, docs/source/users/calc_tutorial.rst, docs/source/users/ps_recon_tutorial.rst, docs/source/users/recon_tutorial.rst, holopy/propagation/convolution_propagation.py, holopy/propagation/point_source_propagate.py, holopy/scattering/calculations.py
Still lots of warnings and syntax errors, but this is a first step.
=> Get all doctests working

docs/source/pyplots/calc_sphere.py
=> change calc_sphere.py

docs/source/users/infer_tutorial.rst
=> fixed several typos in infer_tutorial

docs/source/users/dev_tutorial.rst, docs/source/users/fit_tutorial.rst, docs/source/users/infer_tutorial.rst
=> Fixed a typo in fit_tutorial

.gitignore, requirements.txt, setup.py
Have setup.py draw requirements from requiements.txt and actually attempt to enforce them.
Also get setup.py test working
=> Improve setup.py

docs/source/users/dev_tutorial.rst, holopy/inference/noise_model.py
Also rename _holo in NoiseModel to _forward since NoiseModel can work with
things that are not holograms.
=> Add developer docs for adding an inference model

docs/source/users/install.rst
It might be better to create a manoharan-lab conda channel.
=> windows installation docs

docs/source/users/infer_tutorial.rst
As suggested by @tdimiduk (https://github.com/manoharan-lab/holopy/issues/209#issuecomment-336445072)
Please feel free to edit the text if needed, as English is not my first language.
=> Add documentation on tied priors to the Bayesian inference tutorial

holopy/inference/__init__.py, holopy/inference/result.py, holopy/inference/scipyfit.py, holopy/inference/tests/test_fit.py
Fitting with scipy's least_squares instead of Nmpfit
There is a lot of duplicated or near-duplicated code between NmpfitStrategy and the new LeastSquaresScipyStrategy; this should be cleaned up in the future.
=> Fitwithscipy

holopy/scattering/tests/test_mielensfunctions.py, holopy/scattering/theory/mielensfunctions.py
This PR is just for a few minor clarifications + speedups to the mielens code; there should be no functional difference.
=> Cleanmielens

holopy/core/tests/test_utils_math.py, holopy/core/utils.py
This is my first contribution to #280.
=> Improve testing of utils.py

holopy/scattering/tests/test_mielens.py, holopy/scattering/tests/test_mielensfunctions.py, holopy/scattering/tests/test_scatteringtheory.py
Adding some unit tests to scatteringtheory.py, mielens.py, mielensfunctions.py
=> Testtheory

holopy/core/metadata.py, holopy/core/tests/test_metadata.py, holopy/scattering/tests/test_scatteringtheory.py
This is a pull request for a series of unit tests for test_metadata. 
This pull request is premature; I know there will be some things that need to be fixed but I'd like some advice on how to handle them. I will point them out in comments in the code below. There are 5 of them.
Thanks!
=> Testmetadata

holopy/fitting.py, holopy/inference/emcee.py, holopy/inference/result.py, holopy/inference/tests/common.py, holopy/inference/tests/test_interface.py, holopy/inference/tests/test_nmpfit.py, holopy/scattering/tests/test_dda.py, run_nose.py
Mostly just the super slow one, but I also tinkered with a couple others.
=> speed up tests

holopy/__init__.py, holopy/inference/emcee.py, holopy/inference/tests/test_emcee.py, setup.py
=> Restore emcee<3.0.0 compatibility

holopy/core/io/vis.py, holopy/core/tests/test_vis.py
In reference to #323 I updated the `vis.py` to be able to save generated Plots even for reconstruction volumes.
=> Updatet vis.py to also allow to save generated plots

docs/source/users/theories.rst
=> Fixfailingdoctest

holopy/inference/tests/test_interface.py, holopy/inference/tests/test_prior.py, holopy/scattering/theory/lens.py
Three small commits that fixes #359, fixes #362, and tags a slow test as slow.
=> Fix #359 and #362

docs/source/releasenotes.rst, holopy/inference/model.py, holopy/inference/prior.py, holopy/inference/tests/test_model.py, holopy/inference/tests/test_prior.py
Documentation on using these new things is lacking. We should have a user guides on Model & Prior objects, and also a tutorial using the new features. I'm happy to get this merged in first though
=> Transformed priors

.travis.yml, holopy/__init__.py, holopy/core/io/serialize.py, holopy/core/io/vis.py, holopy/core/tests/test_io.py, holopy/core/tests/test_vis.py, holopy/inference/cmaes.py, holopy/inference/model.py, holopy/inference/result.py, holopy/inference/tests/test_model.py, holopy/scattering/imageformation.py, holopy/scattering/interface.py, holopy/scattering/tests/test_imageformation.py, holopy/scattering/theory/mielens.py
Accidentally pushed this to develop branch (I thought GitHub disallowed this, but clearly trusted it too much). I created a new branch before my changes for the purpose of this PR.
Haven't updated releasenotes - let me know if there's anything here that should be included.
=> Various small changes
